all:
  children:
    masters:
      hosts:
        k8s-master:
          ansible_host: "172.30.1.21"
    workers:
      hosts:
        k8s-worker01:
          ansible_host: "172.30.1.22"
        k8s-worker02:
          ansible_host: "172.30.1.23"
        k8s-worker03:
          ansible_host: "172.30.1.24"

