- name: Assign hosts into /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{inventory_hostname}}$"
    line: "{{ ansible_host }} {{ inventory_hostname }}"
    state: present
  when: ansible_host != inventory_hostname
  delegate_to: localhost
  throttle: 1
  become: true

- name: ssh_keyscan for known hosts file
  command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }} {{ inventory_hostname }}
  register: keyscan
  changed_when: False
  delegate_to: localhost
  throttle: 1

- name: Insert keys
  lineinfile:
    path: "{{ known_hosts_path }}"
    line: "{{ item }}"
    create: yes
  with_items:
    - "{{ keyscan.stdout_lines }}"
  delegate_to: localhost

- name: Adding authorized keys for each servers
  authorized_key:
    user: "{{ ssh_userid }}"
    state: present
    key: "{{ lookup('file', id_rsa_pub_path) }}"

- name: Update hostname for each servers
  hostname:
    name: "{{ inventory_hostname }}"
  become: true

