---

- name: Update apt-get repo and cache
  apt:
    update_cache: True
    force_apt_get: True
    cache_valid_time: 3600

- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: True
  register: apt_result

- name: Remove useless packages
  apt:
    autoremove: True
    purge: True


- name: Reboot systems
  command: "shutdown --reboot +1"
  ignore_errors: yes
  changed_when: False
  when:
    - "'System reboot required' in apt_result.stdout"
