---
- name: Copy the maintenance.sh to each hosts
  copy:
    src: files/maintenance.sh
    dest: "/usr/local/bin/maintenance.sh"
    mode: "0644"
    owner: root
    group: root
  become: true

- name: Register cron job
  cron:
    name: "system maintenance"
    minute: "0"
    job: "/usr/local/bin/maintenance.sh > /dev/null"
    state: present
  become: true

- name: Update apt-get repo and cache
  apt:
    update_cache: True
    force_apt_get: True
    cache_valid_time: 3600

- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: True
  register: apt_result

- name: Install linux-modules-extra-raspi
  apt:
    pkg: linux-modules-extra-raspi
    state: present

- name: Remove useless packages
  apt:
    autoremove: True
    purge: True

- name: Disable SWAP by command
  shell: swapoff -a

- name: Disable SWAP in fstap
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Reboot systems
  command: "shutdown --reboot +1"
  ignore_errors: yes
  changed_when: False
  when:
    - "'System reboot required' in apt_result.stdout"
