- name: restart containerd
  service:
    name: containerd
    state: restarted
  become: true
  listen: "restart contaienrd"

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: true
  listen: "restart nginx"
