---

# Download and install containerd

- name: Download containerd binary
  get_url:
    url: "{{ containerd_url }}"
    dest: "/tmp/{{ containerd_file }}"

- name: Extract containerd binary
  unarchive:
    src: "/tmp/{{ containerd_file }}"
    dest: "/usr/local"
  become: true

- name: Create local systemd directory
  file:
    path: /usr/local/lib/systemd/system
    state: directory
  become: true

- name: Install containerd.service
  template:
    src: templates/containerd.service.j2
    dest: /usr/local/lib/systemd/system/containerd.service
  become: true

- name: Reload containerd.service
  service:
    name: containerd
    daemon_reload: true
  become: true

- name: Generate default containerd config
  command: /usr/local/bin/containerd config default
  register: containerd_conf
  changed_when: False
  become: true

- name: Create /etc/containerd directory
  file:
    path: /etc/containerd
    state: directory
  become: true

- name: Generate /etc/containerd/config.toml
  copy:
    content: "{{ containerd_conf.stdout | replace('SystemdCgroup = false', 'SystemdCgroup = true') | replace('registry.k8s.io/pause:3.6', 'registry.k8s.io/pause:3.2') }}"
    dest: /etc/containerd/config.toml
  become: true

- name: Enable containerd.service
  service:
    name: containerd
    state: restarted
    enabled: true
  become: true
  changed_when: false
